name: fit_weight_app
description: A Flutter web app for calculating loaded weights on barbells.
publish_to: 'none' # Pokud aplikaci nebudeš publikovat jako balíček

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  camera: ^0.10.5
  image_picker: ^1.0.7
  flutter_web_plugins:
    sdk: flutter
  path_provider: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/
